### ISSUE TITLE
Notes keep disappearing

### ISSUE THREAD

**Issue by gabeweisz** [caseydavenport/biermacht#53]
My beer notes keep disappearing. Not sure exactly when, but if I leave the app for awhile all of my notes - in multiple recipes - are gone.

**Comment by caseydavenport** [comment]
@gabeweisz Thanks for raising.  I'll try to reproduce this myself (it will be hard to fix without a reproduction).  To be clear, you're referring to the beer / taste notes that you've saved?

**Comment by caseydavenport** [comment]
My best guess is that there is somewhere in the code that doesn't write the notes properly, so when the recipe is saved the notes are overwritten.  I'll take a look through to see if something stands out.

**Comment by gabeweisz** [comment]
Yes - it is the beer/taste notes. And sometimes they are saved properly for awhile, but I'll open the app and then they're gone. I'll try to reproduce reliably.

**Comment by gabeweisz** [comment]
Got it - if I go into the "edit recipe" screen and click save, the notes go away. I don't need to change anything in the "edit recipe" screen.

**Comment by caseydavenport** [comment]
Fix from #54 will be in next release.
