### ISSUE TITLE
Logo and name Biermacht

### ISSUE THREAD

**Issue by mcmellow** [caseydavenport/biermacht#71]
Hi Casey,

I made a posting on the Dutch Hobby brewers forum about your app. The first reaction was about your logo and the name of your app.  Dutch brewers made a link to nazi Germany and the whermacht of World War 2. Can you please explain the meaning of the logo and the name of this app Biermacht

**Comment by pricelessbrewing** [comment]
Not the developer, but it literally translates to beer maker.

**Comment by caseydavenport** [comment]
> literally translates to beer maker.

Developer here - this was the intention of the name, as in the German "Machen".

**Comment by caseydavenport** [comment]
@mcmellow Thanks for bringing this to my attention. The logo was just meant to be a cool graphic - a bird with the body of a beer bottle. It was a long time ago, but IIRC it was crafted up from a combination of other graphics.

Looking in this light, I do see how it can be misinterpreted. I did not intend to evoke or reference Nazi imagery and I'm sorry for any confusion or offense that was taken as a result. I will look into getting a new graphic made - I definitely do not want users to make this association with my software!

**Comment by mcmellow** [comment]
Hi Casey
Thank very much for your explanation. I did put your answer in the postings. I hope the discussion about the name and the logo will stop now.
I am very happy with your app. No I have the recipes of all my brews in my phone at hand, inculding notes etc. Exporting recipes to my dropbox on my laptop and importing the same recipes from the dropbox on my phone into Biermacht works great.

**Comment by wligtenberg** [comment]
@pricelessbrewing not really at best it would literally translate to beer makes. Beer maker would be something like bier macher. Currently I think most people would translate it to beer power. Which is technically fine, but in German can have negative connotations.
I also immediately noticed Nazi resemblances. I know changing the name is painful, however, the current name and logo do keep me back from contributing.

**Comment by caseydavenport** [comment]
Logo change went in here: https://github.com/caseydavenport/biermacht/pull/72

Should be reflected in the play store in a few hours!

**Comment by mcmellow** [comment]
Dear Casey,

You got my deepest respect for this change, thanks

**Comment by mcmellow** [comment]
Dear Casey,

it is great you changed the logo. You own my deepest respect for this change.  Chapeau!!!
This a Dutch way of saying: I raise my head and bow for you !

**Comment by wligtenberg** [comment]
Thanks, I just had a look at it, and I will be honest. The name is now less of an issue as well.
It really was the combination that triggered it.
