### ISSUE TITLE
question on abv range in details

### ISSUE THREAD

**Issue by 77jeff87** [caseydavenport/biermacht#81]
The details section of the input provides an abv range.  In some of my recipes, the abv range is shown as "22.0 - 6.0" rather than for instance, "x.x - 6.0." What data am I entering incorrectly?

**Comment by caseydavenport** [comment]
@77jeff87 I don't think you're entering anything incorrectly - there was a bug in a recent release which caused this behavior.

If you update to the latest version and then reset the ingredients database from the settings page it should be fixed.

Thanks!
